### ISSUE TITLE
Run rename only for the current project platforms

### ISSUE THREAD

**Issue by tango4567** [onatcipli/rename#14]
Previously this is working properly even I created short [video](https://youtu.be/lT9lwRPhukc) on this as well but recently i switched on MacOs and I found this issue.

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   FileRepository.changeIosBundleId (package:rename/file_repository.dart:55:14)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⚠️       Ios BundleId could not be changed because,
│ ⚠️       The related file could not be found in that path:  ios/Runner.xcodeproj/project.pbxproj
│ ⚠️       
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   FileRepository.changeMacOsBundleId (package:rename/file_repository.dart:79:14)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⚠️       macOS BundleId could not be changed because,
│ ⚠️       The related file could not be found in that path:  macos/Runner/Configs/AppInfo.xcconfig
│ ⚠️       
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   FileRepository.changeAndroidBundleId (package:rename/file_repository.dart:103:14)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⚠️       Android BundleId could not be changed because,
│ ⚠️       The related file could not be found in that path:  android/app/build.gradle
│ ⚠️       
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```

**Comment by onatcipli** [comment]
Hey @tango4567, thank you for the video ✌️  happy to see that 😊 

do you got a stack trace for this error and could you also add your package version number?

**Comment by bdlukaa** [comment]
I also get this. The app get renamed, but I get the error:

```
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   FileRepository.changeIosAppName (package:rename/file_repository.dart:173:12)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 💡 IOS appname changed successfully to : *****
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   FileRepository.changeMacOsAppName (package:rename/file_repository.dart:182:14)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⚠️       macOS AppName could not be changed because,
│ ⚠️       The related file could not be found in that path:  .\macos\Runner\Configs\AppInfo.xcconfig
│ ⚠️       
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   FileRepository.changeAndroidAppName (package:rename/file_repository.dart:223:12)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ 💡 Android appname changed successfully to : *****
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   FileRepository.changeLinuxAppName (package:rename/file_repository.dart:254:14)
│ #1   <asynchronous suspension>
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⚠️       Linux AppName could not be changed because,
│ ⚠️       The related file could not be found in that path:  .\linux\CMakeLists.txt
│ ⚠️
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
```

Probably, the package should verify if the platform is supported before trying to rename it

**Comment by onatcipli** [comment]
okay for that one we can add folder controls to see the current project has which platforms so I will add this one in the next release

**Comment by Syed-Waleed-Shah** [comment]
**This package is what you need 🔥 Too much flexibilities <br>**
https://pub.dev/packages/rename_app <br>
*Rename App The only flutter package which changes app name for all platforms with sound null safety! If you want to autmatically change your flutter app name with a single command then you are at the right pacakge. This package gives you too many flexibilities through too many variants of its commands. Read the details below to know in more details*

**✊ Dont forget to star the github repo if you found this package useful 😇** 

**Features 🔥** <br>
✅ Remane Android Project <br> ✅ Remane IOS Project <br> ✅ Remane WEB Project <br> ✅ Remane Windows Project

**How To Rename ? 🛠**

**1) ADD THE PACKAGE TO DEPENDENCIES IN pubspec.yaml** 
<br>`flutter pub add rename_app `
<br>
OR
<br>
`dependencies: 
   rename_app: ^latest_version` <br><br>
**2) PROVIDE THE APP NAME <br>**
You can provide app name in the following ways

 - Same name for all apps<br>

> `flutter pub run rename_app:main all="My App Name"`

 - Seperate name for specified platform(s) and same for all others <br>

> `flutter pub run rename_app:main android="Anroid Name" ios="IOS Name"
> others="Others Name"`

 - Seperate name for each platform <br>

> `flutter pub run rename_app:main android="Android Name" ios="IOS Name"
> web="Web Name" mac="Mac Name" windows="Windows Name"`

**Comment by onatcipli** [comment]
this issue is outdated, please try the latest version and if there are any issues feel free the open it again! rename `2.1.1`
